# Generated by Django 5.0.2 on 2024-09-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.CharField(default='https://images.pexels.com/photos/360591/pexels-photo-360591.jpeg?cs=srgb&dl=pexels-markusspiske-360591.jpg&fm=jpg', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.ManyToManyField(to='final.media'),
        ),
    ]
