# Generated by Django 5.0.2 on 2024-09-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_media_project_body_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.ManyToManyField(default=None, to='final.media'),
        ),
    ]
