# Generated by Django 5.0.2 on 2024-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_alter_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.ManyToManyField(blank=True, related_name='link', to='final.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
