# Generated by Django 5.0.2 on 2024-09-06 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_remove_media_url_remove_project_url_media_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='final.project'),
        ),
    ]
