# Generated by Django 5.0.2 on 2024-09-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0008_remove_media_project_project_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='media',
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='final.project'),
        ),
    ]
