# Generated by Django 5.0.2 on 2024-09-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0009_remove_project_media_alter_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='project',
            field=models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='final.project'),
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
