# Generated by Django 5.0.2 on 2024-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0010_media_project_alter_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='resource',
            field=models.CharField(default='placeholder', max_length=500),
            preserve_default=False,
        ),
    ]
