# Generated by Django 5.0.2 on 2024-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0011_media_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='resourceTitle',
            field=models.CharField(default='placeholder', max_length=150),
            preserve_default=False,
        ),
    ]
