# Generated by Django 5.0.2 on 2024-09-11 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0014_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Message',
        ),
    ]
