# Generated by Django 5.0.2 on 2024-09-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0016_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=150)),
                ('project', models.ForeignKey(max_length=150, null=True, on_delete=django.db.models.deletion.CASCADE, to='final.project')),
            ],
        ),
    ]
