# Generated by Django 5.0.2 on 2024-09-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0017_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
